(async function(){'use strict';const r=await fetch('data.json'),D=await r.json();
document.getElementById('logo').innerHTML='<svg width="26" height="26" viewBox="0 0 100 100" fill="none"><rect width="100" height="100" rx="20" fill="#1E3D2F"/><path d="M50 20C38 20 28 30 28 42s10 22 22 22 22-10 22-22-10-22-22-22z" fill="#C8A25A" opacity=".85"/><path d="M36 52c0 0 6 24 14 32s14-32 14-32" stroke="#C8A25A" stroke-width="4" fill="none" stroke-linecap="round"/></svg>'+D.site.nome;
document.getElementById('menu').innerHTML=D.menu.map(m=>'<a href="'+m.href+'">'+m.rotulo+'</a>').join('');
const tr=document.getElementById('carTr');tr.innerHTML=D.slides.map(s=>{const i=s.img?'<img src="'+s.img+'" onerror="this.style.display=\'none\'">':'<div style="position:absolute;width:100%;height:100%;background:linear-gradient(135deg,#1E3D2F,#2D5A3E)"></div>';return'<div class="cr-sl">'+i+'<div class="o"></div><div class="cr-c"><h1>'+s.titulo+'</h1><p>'+s.texto+'</p><a href="#'+['','produtos','assinaturas','conteudo'][D.slides.indexOf(s)+1]+'" class="btn">'+s.btn+' <i class="fas fa-arrow-right"></i></a></div></div>';}).join('');
const dt=document.getElementById('carDots');dt.innerHTML=D.slides.map((_,i)=>'<button class="cr-d'+(i===0?' a':'')+'" data-i="'+i+'"></button>').join('');
let ci=0,sl=D.slides.length,iv;function go(i){if(i<0)i=sl-1;if(i>=sl)i=0;ci=i;tr.style.transform='translateX(-'+(ci*100)+'%)';dt.querySelectorAll('.cr-d').forEach((d,j)=>d.classList.toggle('a',j===ci));}
dt.querySelectorAll('.cr-d').forEach(d=>d.addEventListener('click',()=>{clearInterval(iv);go(parseInt(d.dataset.i));iv=setInterval(()=>go(ci+1),5000);}));
document.getElementById('carPr').addEventListener('click',()=>{clearInterval(iv);go(ci-1);iv=setInterval(()=>go(ci+1),5000);});
document.getElementById('carNx').addEventListener('click',()=>{clearInterval(iv);go(ci+1);iv=setInterval(()=>go(ci+1),5000);});
iv=setInterval(()=>go(ci+1),5000);
document.getElementById('prodGrid').innerHTML=D.produtos.map(p=>'<div class="pc" data-id="'+p.id+'" data-n="'+p.nome+'" data-p="'+p.preco+'" data-i="'+p.img+'"><img src="'+p.img+'" onerror="this.style.display=\'none\'"><div class="pc-b"><div class="pc-c">'+p.cat+'</div><h3>'+p.nome+'</h3><p>'+p.desc+'</p><div class="pc-f"><span class="pr">R$ '+p.preco.toFixed(2).replace('.',',')+'</span><button class="btn-sm ac">Adicionar</button></div></div></div>').join('');
document.getElementById('servGrid').innerHTML=D.servicos.map(s=>'<div class="sc"><div class="sc-i"><i class="fas '+s.icone+'"></i></div><h3>'+s.titulo+'</h3><p>'+s.desc+'</p></div>').join('');
document.getElementById('subGrid').innerHTML=D.assinaturas.map(a=>'<div class="sbc" data-id="'+a.id+'" data-n="'+a.nome+'" data-p="'+a.preco+'" data-i="'+a.img+'"><img src="'+a.img+'" onerror="this.style.display=\'none\'"><div class="sbc-b"><span class="sbc-bdg '+a.badge+'">'+a.badge_txt+'</span><h3>'+a.nome+'</h3><p>'+a.desc+'</p><span class="sbc-p">R$ '+a.preco.toFixed(2).replace('.',',')+' <small>/mês</small></span><button class="btn-sm btn-sm-f ac">Assinar</button></div></div>').join('');
document.getElementById('contGrid').innerHTML=D.conteudos.map((c,i)=>'<div class="ctc" data-idx="'+i+'"><img src="'+c.img+'" onerror="this.style.display=\'none\'"><div class="ctc-b"><div class="ctc-t">'+c.cat+'</div><h3>'+c.titulo+'</h3><p>'+c.data+' · '+c.min+' min</p></div></div>').join('');
document.getElementById('depGrid').innerHTML=D.depoimentos.map(d=>'<div class="tc"><img src="'+d.img+'" onerror="this.style.display=\'none\'"><q>'+d.frase+'</q><div class="au">'+d.autor+'</div><div class="lo">'+d.local+'</div></div>').join('');
const fg=document.getElementById('ftGrid');fg.innerHTML='<div><svg width="24" height="24" viewBox="0 0 100 100" fill="none"><rect width="100" height="100" rx="20" fill="#C8A25A"/><path d="M50 20C38 20 28 30 28 42s10 22 22 22 22-10 22-22-10-22-22-22z" fill="#1E3D2F" opacity=".85"/><path d="M36 52c0 0 6 24 14 32s14-32 14-32" stroke="#C8A25A" stroke-width="4" fill="none" stroke-linecap="round"/></svg><div class="ft-br">'+D.site.nome+'</div><p class="ft-d">Curadoria de produtos e serviços com respeito e elegância.</p><div class="ft-s">'+D.redes.map(r=>'<a href="'+r.url+'"><i class="fab '+r.icone+'"></i></a>').join('')+'</div></div>';
[{t:'Produtos',l:[{t:'Farmácia',u:'#produtos'},{t:'Alimentos',u:'#produtos'},{t:'Orgânicos',u:'#produtos'}]},{t:'Serviços',l:[{t:'Motorista',u:'#servicos'},{t:'Saúde',u:'#servicos'},{t:'Concierge',u:'#servicos'}]},{t:'Contato',l:[{t:D.site.telefone,u:'tel:'+D.site.telefone},{t:D.site.email,u:'mailto:'+D.site.email}]}].forEach(c=>{fg.innerHTML+='<div><h4>'+c.t+'</h4><ul>'+c.l.map(l=>'<li><a href="'+l.u+'">'+l.t+'</a></li>').join('')+'</ul></div>';});
document.getElementById('ftBot').textContent='© 2026 '+D.site.nome+'. Todos os direitos reservados.';
let cart=JSON.parse(localStorage.getItem('cart')||'[]');
function sv(){localStorage.setItem('cart',JSON.stringify(cart));}
function up(){sv();const tl=cart.reduce((s,i)=>s+i.p*i.q,0),ct=cart.reduce((s,i)=>s+i.q,0);document.getElementById('cartNum').textContent=ct;document.getElementById('cartTot').textContent='R$ '+tl.toFixed(2).replace('.',',');document.getElementById('cartFt').style.display=ct?'block':'none';const el=document.getElementById('cartIt');if(!cart.length){el.innerHTML='<p class="e">Seu carrinho está vazio.</p>';return;}el.innerHTML=cart.map((item,i)=>'<div class="ct-it"><img src="'+item.i+'" onerror="this.style.display=\'none\'"><div class="ct-it-i"><div class="ct-it-n">'+item.n+'</div><div class="ct-it-p">R$ '+item.p.toFixed(2).replace('.',',')+'</div><div class="ct-it-q"><button onclick="window.ac.q('+i+',-1)">−</button><span>'+item.q+'</span><button onclick="window.ac.q('+i+',1)">+</button></div></div><button class="ct-it-r" onclick="window.ac.r('+i+')"><i class="fas fa-trash-alt"></i></button></div>').join('');}
window.ac={add:(id,n,p,i)=>{const e=cart.find(x=>x.id===id);if(e)e.q++;else cart.push({id,n,p,i,q:1});up();tt('Adicionado ao carrinho!');},r:i=>{cart.splice(i,1);up();},q:(i,d)=>{cart[i].q+=d;if(cart[i].q<=0)cart.splice(i,1);up();}};
document.addEventListener('click',e=>{const b=e.target.closest('.ac');if(b){e.stopPropagation();const c=b.closest('[data-id]');if(c)window.ac.add(c.dataset.id,c.dataset.n,parseFloat(c.dataset.p),c.dataset.i||'');}});
document.getElementById('cartBtn').addEventListener('click',()=>{document.getElementById('cartSd').classList.add('on');document.getElementById('cartOv').classList.add('on');});
function cc(){document.getElementById('cartSd').classList.remove('on');document.getElementById('cartOv').classList.remove('on');}
document.getElementById('cartCl').addEventListener('click',cc);document.getElementById('cartOv').addEventListener('click',cc);
document.getElementById('cartChk').addEventListener('click',()=>{if(!cart.length)return;const m=cart.map(i=>i.n+' x'+i.q+' = R$'+(i.p*i.q).toFixed(2)).join('\n');const t=cart.reduce((s,i)=>s+i.p*i.q,0);window.open('https://wa.me/'+D.site.telefone.replace(/[^0-9]/g,'')+'?text=Olá! Quero finalizar meu pedido:%0A'+encodeURIComponent(m)+'%0A%0ATotal: R$ '+t.toFixed(2).replace('.',','),'_blank');});
up();function tt(m){const t=document.createElement('div');t.className='tt s';t.textContent=m;document.body.appendChild(t);setTimeout(()=>{t.classList.remove('s');setTimeout(()=>t.remove(),300);},2000);}
const mod=document.getElementById('mod'),ov=document.getElementById('modOv'),mb=document.getElementById('modBd');
function abrir(h){mb.innerHTML=h;mod.classList.add('on');ov.classList.add('on');document.body.style.overflow='hidden';}
function fechar(){mod.classList.remove('on');ov.classList.remove('on');document.body.style.overflow='';}
document.getElementById('modCl').addEventListener('click',fechar);ov.addEventListener('click',fechar);
document.querySelectorAll('.ctc').forEach(el=>{el.addEventListener('click',()=>{const c=D.conteudos[parseInt(el.dataset.idx)];if(c)abrir('<div class="ctc-t">'+c.cat+'</div><h2>'+c.titulo+'</h2><img src="'+c.img+'" onerror="this.style.display=\'none\'">'+c.html);});});
document.querySelectorAll('.pc').forEach(el=>{el.addEventListener('click',function(){const p=D.produtos.find(x=>x.id===parseInt(this.dataset.id));if(p)abrir('<img src="'+p.img+'" onerror="this.style.display=\'none\'"><div class="pc-c">'+p.cat+'</div><h2>'+p.nome+'</h2><p style="font-size:.9rem;line-height:1.7;color:#6e6e73;margin-bottom:18px">'+p.desc+'</p><div class="p-lg">R$ '+p.preco.toFixed(2).replace('.',',')+'</div><button class="btn btn-f ac" data-id="'+p.id+'" data-n="'+p.nome+'" data-p="'+p.preco+'" data-i="'+p.img+'">Adicionar ao carrinho</button>');});});
document.getElementById('newsForm').addEventListener('submit',e=>{e.preventDefault();tt('Inscrição realizada com sucesso!');e.target.querySelector('input').value='';});
document.querySelectorAll('a[href^="#"]').forEach(a=>{a.addEventListener('click',e=>{const t=document.querySelector(a.getAttribute('href'));if(t){e.preventDefault();t.scrollIntoView({behavior:'smooth'});}});});})();
